name: Build LaTeX document

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: seminarthesis.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: seminarthesis.pdf
  release_pdf:
    name: Release PDF
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: PDF
    - name: Create Github realse
      id: new_release_id
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        upload_url: ${{ steps.new_release_id.outputs.upload_url }}
        asset_path: seminarthesis.pdf
        asset_name: seminarthesis.pdf
        asset_content_type: application/pdf
