name: Build LaTeX document

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - '**/README.md'


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: seminarthesis.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: seminarthesis.pdf
  release:
    name: Release PDF
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: PDF
    - name: Display structure of downloaded files
      run: ls -R
